### ISSUE TITLE
Failed to resolve entry for package

### ISSUE THREAD

**Issue by tboerger** [mentaljam/rollup-plugin-copy2#7]
With the latest release I'm receiving an error if Renovate tries to update the dependencies where I'm not sure where the error really comes from:

```
Error: R] Failed to resolve entry for package "rollup-plugin-copy2". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1360:27:
      1360 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///home/runner/work/kleister-ui/kleister-ui/node_modules/vite/dist/node/chunks/dep-[9](https://github.com/kleister/kleister-ui/actions/runs/4962081310/jobs/8879690649?pr=130#step:6:10)34dbc7c.js:23384:11)
    at resolvePackageEntry (file:///home/runner/work/kleister-ui/kleister-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23381:5)
    at tryNodeResolve (file:///home/runner/work/kleister-ui/kleister-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23115:20)
    at file:///home/runner/work/kleister-ui/kleister-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:64385:40
    at requestCallbacks.on-resolve (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:1360:28)
    at handleRequest (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/runner/work/kleister-ui/kleister-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:64374:27)
    at handlePlugins (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:776:5)
    at /home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:2163:15
    at new Promise (<anonymous>)
    at Object.build (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:2162:25)
    at build (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:2011:51)
    at bundleConfigFile (file:///home/runner/work/kleister-ui/kleister-ui/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:64337:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.js:7:17:
      7 │ import copy from "rollup-plugin-copy2";
        ╵                  ~~~~~~~~~~~~~~~~~~~~~

failed to load config from /home/runner/work/kleister-ui/kleister-ui/vite.config.js
error during build:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1360:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "rollup-plugin-copy2". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:1636:15)
    at /home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:[10](https://github.com/kleister/kleister-ui/actions/runs/4962081310/jobs/8879690649?pr=130#step:6:11)48:25
    at runOnEndCallbacks (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:1046:7)
    at /home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/home/runner/work/kleister-ui/kleister-ui/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:[12](https://github.com/kleister/kleister-ui/actions/runs/4962081310/jobs/8879690649?pr=130#step:6:13))
Error: Process completed with exit code 1.
```

You can see the changes made by Renovate at https://github.com/kleister/kleister-ui/pull/130 and the related configuration at https://github.com/kleister/kleister-ui/blob/master/vite.config.js#L79-L81. Hopefully somebody could give me the right hint?

**Comment by qgates** [comment]
Same issue here with Vite 4.3.8.

v0.4.0 is broken with Vite, Rolling back to v0.3.1 everything works fine.

**Comment by tboerger** [comment]
I have replaced the dependency now.
